### PR TITLE
MSSQL ODBC // fixed #383 - long lines insert/select

### LINKED ISSUE #383: std::strings in nvarchar(max) is still a problem
Reading string trough ODBC version 11 still does not work for nvarchar(max) columns (yes I'm aware of issue #287). ODBC version 10 works just fine.

Environment:
windows 8.1
msvc 2013
soci version 4 (from 8-Sep-2015)

Database setup:
use history
create table test ( data nvarchar (MAX) not null );
insert into test (data) values ('Aaa')

Test source code:

```
#define SOCI_USE_BOOST
#include <soci.h>            // SOCI components
#include <soci-config.h>
#include <odbc/soci-odbc.h>
#include <afxcontrolbars.h>
using namespace soci;

//const char* connectionString = "DRIVER={SQL Server};Server=192.168.11.54\\SPSQL;Uid=sa;Pwd=Master10"; //<<<<this works
const char* connectionString = "DRIVER={ODBC Driver 11 for SQL Server};Server=192.168.11.54\\SPSQL;Uid=sa;Pwd=Master10"; //<<<<THIS DOESN'T WORK

    session sql;
    sql.open(connection_parameters("odbc", connectionString));

    sql << "use history";

    rowset<row> rs = sql.prepare << "select * from test";
    for (auto it = rs.begin(); it != rs.end(); ++it)
    {
        std::string data;
        data = it->get<std::string>("data"); //this returns empty string if ODBC 11 is used
    }
```

### PR DESCRIPTION
**Pull request by snikulov**
Fixed failed tests for ODBC long lines usage.

### CODE REVIEW

File: src/backends/odbc/standard-use-type.cpp [hunk 1]
```diff
@@ -212,14 +211,20 @@ void odbc_standard_use_type_backend::pre_use(indicator const *ind)
     SQLSMALLINT sqlType(0);
     SQLSMALLINT cType(0);
     SQLLEN size(0);
+    SQLLEN bufLen(0);
 
     void* const sqlData = prepare_for_bind(size, sqlType, cType);
-
+    if (sqlType == SQL_LONGVARCHAR)
```
Comment (vadz) [inline src/backends/odbc/standard-use-type.cpp]: Even if we want to do it like this, it doesn't make much sense to do it like this: why explicitly set `sqlType` to `SQL_LONGVARCHAR` inside `prepare_for_bind()` only to reset it to `SQL_VARCHAR` here? Instead, the code in `prepare_for_bind()` added by c025cc86 should be simply reverted.

But I am not sure if doing this would be correct, after all it wasn't added without reason and did fix #287, so I'm afraid doing this might reintroduce that bug. It looks like there might be a difference in behaviour between ODBC 10 and 11 here, has this patch (and the "long string" ODBC unit test) been tested with both 10 and 11?

Comment (snikulov) [inline src/backends/odbc/standard-use-type.cpp]: Because with SQL_LONGVARCHAR it still have issue.
I've checked on both 10 on AppVeyor, and 11 - locally on Win 10, sql express 2016 - all works, fine as you can see.

Another option come into my mind - operates only with sizeof and move check for long ```size > 8000``` after ```prepare_for_bind```.

Anyway it solves the long standing issue - even if you don't like it.

**Comment by snikulov** [comment]
@vadz Updated per your comments.
Now it looks better.

File: src/backends/odbc/standard-use-type.cpp [hunk 2]
```diff
@@ -212,14 +203,19 @@ void odbc_standard_use_type_backend::pre_use(indicator const *ind)
...
     SQLSMALLINT cType(0);
     SQLLEN size(0);
+    SQLLEN bufLen(0);
 
     void* const sqlData = prepare_for_bind(size, sqlType, cType);
-
+    if (size > ODBC_MAX_COL_SIZE)
+    {
+        bufLen = size;
+        size = 0;
```
Comment (vadz) [inline src/backends/odbc/standard-use-type.cpp]: I think it would be more clear if the comment about this 0 actually being `SQL_SS_LENGTH_UNLIMITED` were kept.

**Comment by vadz** [comment]
Of course it doesn't matter whether or not I "like" it, if it works for both versions, then this is the right thing to do. I just wasn't sure it was still working for v10 too, thanks for testing and verifying that it did!

FWIW I still don't fully understand what's going on here, e.g. [this MSDN article](https://msdn.microsoft.com/en-us/library/ms131462.aspx) only mentions that `ColumnSize` must be set to 0 for `varchar(max)`, but says nothing about `BufferLength`. But this wouldn't be the first time MSDN documentation wasn't 100% accurate and complete...

Anyhow, I don't have any other remarks about this, thank you for fixing this bug!

File: src/backends/odbc/standard-use-type.cpp (hunk 2 above)
Comment (snikulov) [inline src/backends/odbc/standard-use-type.cpp]: I've updated to use ```SQL_SS_LENGTH_UNLIMITED``` and since it not defined on my MSVC2015/Win10, I also added this defined in our soci-odbc.h

**Comment by snikulov** [comment]
@vadz @mloskot final changes with updates rebased into single change.
Could you please review? If no objections, I'll merge it to master.

File: include/soci/odbc/soci-odbc.h [hunk 3]
```diff
@@ -33,6 +33,10 @@
 #include <sqlext.h> // ODBC
 #include <string.h> // strcpy()
 
+#ifndef SQL_SS_LENGTH_UNLIMITED
```
Comment (mloskot) [inline include/soci/odbc/soci-odbc.h]: Since this define is SQLNCLI driver-specific, it is not defined in `sql.h`, but in `sqlncli.h`, similarly to `SQL_SS_UDT` and others. Part of the ODBC mess.

In `sqlncli.h` it is defined as follows:
```
// SQL_SS_LENGTH_UNLIMITED is used to describe the max length of
// VARCHAR(max), VARBINARY(max), NVARCHAR(max), and XML columns
#define SQL_SS_LENGTH_UNLIMITED             0
```

The PR looks good to me. Thanks!

**Comment by vadz** [comment]
Just to repeat, I don't have any further comments, thanks!

**Comment by snikulov** [comment]
Ok. Merged on master.
